sudo: required
services:
  - docker

befor_install:
  - docker build -t khalesi1369/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true khalesi1369/docker-react npm run test -- --coverage
